# Change these first
owner: YasirArisM # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: YasirPedia API
    url: https://yasirapi.eu.org
  - name: Yasir RoBot
    url: https://tg.yasirweb.biz.id
  - name: Torrent API
    url: https://tor.yasirapi.eu.org
  - name: Webss API
    url: https://webss.yasirapi.eu.org
  - name: URL Shortener
    url: http://url.yasirweb.eu.org
  - name: Paste API
    url: https://paste.yasirapi.eu.org/
  - name: Personal Blog
    url: https://yasirweb.eu.org
  - name: Landing Page
    url: https://yasirpedia.eu.org
  - name: Subscene Mirror
    url: https://sub.yasirweb.eu.org
  - name: Git Server
    url: https://git.yasirweb.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.yasir.eu.org
  # baseUrl: /your-repo-name
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: YasirPedia Site Status
  introTitle: "**Status Dashboard** is the place where you can see all my site uptime status."
  introMessage: This status is **real-time**, [Donation are welcome](https://t.me/s/BeriKopi) to keep all site online.
  navbar:
    - title: Home
      href: /
    - title: Blog
      href: https://yasirweb.eu.org
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Telegram
      href: https://t.me/Yasir_ID

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
